name: Setup Python Environment
run-name: ${{ github.actor }} is creating new Python environment
on: [push]
jobs:
  Setup-Python-Environment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.8'
      - name: Install all packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          python -m pip install cython
          python -m pip install -r requirements.txt
          python -m pip install pystan==2.14
          python -m pip install prophet fbprophet
      - name: Run main script
        run: python main.py