name: Setup Python Environment
run-name: ${{ github.actor }} is creating new Python environment
on: [push]
jobs:
  Setup-Python-Environment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          sudo apt-get update -yq
          sudo apt-get upgrade -yq
          sudo apt-get install gcc libpq-dev -yq
          sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -yq
          sudo apt-get install make build-essential libssl-dev zlib1g-dev libbz2-dev -yq
          sudo apt-get install libreadline-dev libsqlite3-dev wget curl llvm libncursesw5-dev -yq
          sudo apt-get install xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev -yq
      - name: Install all packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools==59.8.0
          python -m pip install --upgrade wheel
          python -m pip install --upgrade cython
          python -m pip install --upgrade cmake
          python -m pip install -r requirements.txt
          python -m pip install pystan~=2.14
          python -m pip install prophet fbprophet
      - name: Run main script
        run: python -m jupyter nbconvert --to python pfs.ipynb